### ISSUE TITLE
meta-issue: change to 18f-pages

### ISSUE THREAD

**Issue by gbinal** [18F/onepage-opensource#3]
Hey @edmullen.  

Any thoughts on changing this repo so that it's using 18F Pages?  

Benefits are: 
- the page would be live at https://pages.18f.gov/onepage-opensource.  
- people could see and share it much more easily.  
- hosting would be taken care of.  
- it would allow for pull requests a lot more easily.  

I could do this for you in just a few minutes if you're game.

**Comment by edmullen** [comment]
I'm game @gbinal. I just haven't taken the time to figure that out. I'd appreciate the help if it's quick for you. Will it continually update as the repo changes, or will I need to manually trigger it in the future?

**Comment by gbinal** [comment]
It's automatic.  

If you're curious, I can walk you through activating it but am also more than happy to just do it for you.  I'd need admin permissions to the repo though (which I think you could give me, or I can ask for in #admins-github).

**Comment by edmullen** [comment]
You're an admin now. If it's very fast for you, I'd appreciate the help, but I might ping you later for future use.

**Comment by gbinal** [comment]
No problem.  Start timing me ... now.

**Comment by gbinal** [comment]
Done - https://pages.18f.gov/onepage-opensource/
